#! /usr/local/bin/python3

def course_lists_to_tables(course_lists):
  """ A course list, generated by dgw_utils.build_course_list() is an object with the following
      structure:
        {'object_type': 'course_list',
         'scribed_courses': [],
         'list_type': AND | OR,
         'list_qualifiers': [],
         'label': None | str,
         'active_courses': [],
         'attributes': [],
         'context_path': str }
      This function generates an HTML table for displaying the scribed and active_courses lists.
  """
  if len(course_lists['scribed_courses']) > 0:
    scribed_table = """
<table><tr><th>Course</th><th>With</th></tr>
"""
    for scribed_course in course_lists['scribed_courses']:
      scribed_table += """
  <tr>
    <td>{} {}</td>
    <td>{}</td>
  </tr>
""".format(scribed_course['discipline'],
           scribe_course['catalog_number'],
           scribed_course['with_clause'])
    scribed_table += '</table>'
  else:
    scribed_table = '<p class="error">Error: There are no scribed courses.</p>'

  if len(course_lists['active_courses']) > 0:
    active_table = """
<table><tr><th>Course</th><th>With</th></tr>
"""
    for active_course in course_lists['active_courses']:
      active_table += """
  <tr>
    <td>{} {}</td>
    <td>{}</td>
  </tr>
""".format(active_course['discipline'],
           active_course['catalog_number'],
           active_course['with_clause'])
    active_table += '</table>'
  else:
    active_table = '<p>There are no active courses for this list.</p>'

  return {'scribed_courses': scribed_table,
          'active_courses': active_table}
