#! /usr/local/bin/bash

# Restart apache because “something” is causing it to crash.
# Launchctl runs this hourly.

echo -e "\n$(date)"
ps aux | ack 'httpd -D'| echo $(wc -l) processes
if command -v brew >/dev/null 2>&1; then
  brew services restart httpd
fi
