#! /usr/local/bin/bash

# Restart both apache and the app because “something” is causing them to crash.
# Launchctl runs this at 5 am daily.
# Trying long delays to see if they make the process more reliable.

# Block external requests to the app
if command -v brew >/dev/null 2>&1; then
    brew services stop httpd
fi

# (Re-)start the app (./start first kills the app if it is running)
./start
# Allow time for it to initialize before sending it more requests
sleep 10

# Re-enable external requests
if command -v brew >/dev/null 2>&1; then
    brew services start httpd
fi
