#! /usr/local/bin/bash

# Restart both apache and the app because “something” is causing them to crash.
# Launchctl runs this at 5 am daily.
# Trying long delays to see if they make the process more reliable.

if command -v brew >/dev/null 2>&1; then
    brew services stop httpd
fi

./stop
sleep 30
./start
sleep 30

if command -v brew >/dev/null 2>&1; then
    brew services start httpd
fi
