#! /usr/local/bin/bash
# Stop gunicorn
if [[ -r gunicorn.pid ]]
then
  if ps -p "$(cat gunicorn.pid)" > /dev/null
  then
    kill "$(cat gunicorn.pid)"
    echo Killed "$(cat gunicorn.pid)"
  else
    echo Removed stale pid "$(cat gunicorn.pid)"
  fi
else
  echo No process to stop
fi
rm -f gunicorn.pid
