#! /usr/local/bin/bash
# Stop gunicorn
if [[ -r gunicorn.pid ]]
then
  pid=`cat gunicorn.pid`
  kill $pid 2> /dev/null
  [[ $? == 0 ]] && echo killed $pid
else
  echo Not running
fi
rm -f gunicorn.pid
