#! /usr/local/bin/bash
for file in *.csv
do file_date=${file: 4:10}
  if [[ $file_date < `/usr/local/opt/coreutils/libexec/gnubin/date -I -d 'yesterday'` ]]
  then echo $file is old and will nevermore be seen
       rm $file
  fi
done

